git:
    submodules: false

# branches:
#     only: master

notifications:
    email: false

language: generic

before_install:
    - sudo apt update
    - sudo apt install nodejs npm
    - sudo pip install --upgrade pip
    - sudo pip install Sphinx
    - sudo pip install sphinxcontrib-inlinesyntaxhighlight
    - sudo pip install sphinx-sitemap
    - sudo apt install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
    - git clone https://github.com/FreeFem/FreeFem-parser-pygments.git ~/pygments
    - sudo cp ~/pygments/freefem.py /usr/local/lib/python2.7/dist-packages/pygments/lexers/
    - cd /usr/local/lib/python2.7/dist-packages/pygments/lexers/ && sudo python _mapping.py
    - cd /home/travis/build/FreeFem/${GH_REPOSITORY}

script:
    # - SPHINXOPTS='-n -b linkcheck' make -e html
    - make html
    - make latex
    - echo "doc.freefem.org" > build/html/CNAME
    - cd build/latex && pdflatex -interaction=nonstopmode -jobname FreeFEM-documentation FreeFEM.tex && pdflatex -interaction=nonstopmode -jobname FreeFEM-documentation FreeFEM.tex && cd ../..
    - mkdir build/html/pdf && cp build/latex/FreeFEM-documentation.pdf build/html/pdf/
    - md5sum  build/html/pdf/FreeFEM-documentation.pdf >> build/html/pdf/FreeFEM-documentation.pdf.md5
    
deploy:
    - provider: pages
      skip-cleanup: true
      github-token: ${GH_TOKEN}
      local-dir: build/html/
      target-branch: gh-pages
      keep-history: true
    - provider: pages
      skip-cleanup: true
      github-token: ${GH_TOKEN}
      local-dir: build/latex/
      target-branch: pdf
      keep-history: true
